name: Build PHP Base FPM Trixie Image

on:
  workflow_dispatch:
    inputs:
      php_version:
        description: "PHP版本"
        required: true
        default: "8.4"
      tag:
        description: "镜像标签"
        required: true
        default: "latest"

jobs:
  build-php84-base-fpm-trixie:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ github.event.inputs.php_version }}
      TAG: ${{ github.event.inputs.tag }}
      REGISTRY_DOCKERHUB: docker.io/jiaoio
      REGISTRY_REDHAT: quay.io/jiaoio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to RedHat Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.REDHAT_REGISTRY_USERNAME }}
          password: ${{ secrets.REDHAT_REGISTRY_TOKEN }}

      - name: Build and push php-base-fpm-trixie multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: ./php-base-fpm-trixie
          platforms: linux/amd64,linux/arm64
          build-args: |
            CHANGE_SOURCE=false
          push: true
          tags: |
            ${{ env.REGISTRY_DOCKERHUB }}/php-base-fpm-trixie:${{ env.PHP_VERSION }}-${{ env.TAG }}
            ${{ env.REGISTRY_DOCKERHUB }}/php-base-fpm-trixie:${{ env.PHP_VERSION }}-fpm-${{ env.TAG }}
            ${{ env.REGISTRY_DOCKERHUB }}/php-base-fpm-trixie:${{ env.PHP_VERSION }}-latest
            ${{ env.REGISTRY_REDHAT }}/php-base-fpm-trixie:${{ env.PHP_VERSION }}-${{ env.TAG }}
            ${{ env.REGISTRY_REDHAT }}/php-base-fpm-trixie:${{ env.PHP_VERSION }}-fpm-${{ env.TAG }}
            ${{ env.REGISTRY_REDHAT }}/php-base-fpm-trixie:${{ env.PHP_VERSION }}-latest
